### PR TITLE
Higher-level API for querying data

### PR DESCRIPTION
**Pull request by bill-ahmed**
This PR provides the ability to query data from all existing APIs via a MongoDB-like syntax. All query classes inherit from `Base`, and with the help of a `QueryBuilder` and some other helper methods, a user can do queries like:

```typescript
import { Courses } from nikel;

// Course for id='CSCA08'
Courses.where({ id: 'CSCA08' }).get();

// More verbously
Courses.where({ id: { '$eq': 'CSCA08' } }).get();
```

The `QueryBuilder` allows for stacking as many queries as desired, with currently no limit on a depth. These queries can therefore get arbitrarily complex, although this new format should help organize them better.

Checkout the `README.md` under `src/models/` for more details and usage examples.

### CODE REVIEW

**Comment by bill-ahmed** [comment]
This PR is still in progress, just need to hook up the `limit()` and `offset()` operators from the `QueryBuilder`, and maybe do some cleanup/refactoring.

**Comment by darenliang** [comment]
This is a pretty good idea! Since most Node.js/js devs use MongoDB as their database of choice, query will be much more familiar.

It would be great if it is possible to support both query formats, either though reflection or through a different method call.

This change might end up be a pretty significant change that'll need a major version bump.

**Comment by darenliang** [comment]
This is a pretty good idea! Since a lot of Node.js/js devs use MongoDB as their database of choice, querying will be much more familiar.

It would be great if it is possible to support both query formats, either though reflection or through a different method call.

This change might end up be a pretty significant change that'll need a major version bump.

**Comment by bill-ahmed** [comment]
The traditional APIs are still very much there, so using them would be a quick `import` away. I've tried to make the newer API extendable, adding a new operator or functionality should be pretty straight forward.

Also, since all the queries compile to a query string (as outlined in the docs), changing the behaviour of certain queries would be pretty easy from the API that's ingesting the request...whether that's a good thing or not lol.

**Comment by bill-ahmed** [comment]
I would like to start adding some unit tests as well, just so there's a back bone for future changes. Although likely in the next PR.

**Comment by darenliang** [comment]
Yep, unittests are definitely helpful. Not sure what testing framework to use though. Maybe `ts-jest` could work, but I think this should come at a later time.

**Comment by darenliang** [comment]
In hindsight, I'm not sure how powerful the querying syntax should be.

It could be possible to implement post-processing on Axios responses so queries can do multiple API calls filter results locally. However, it'll probably result in a complicated implementation and maybe the added complexity might be a bad thing.

**Comment by bill-ahmed** [comment]
Given the schema's are fairly simple at the moment, I don't see much room for complex queries. This newer API is currently schema-agnostic so we could add some validations in the future to constrain what users can request for. 

And yep the approach with doing multiple queries may complicate things. Not sure if I have this right, but are the object being served by nikel-api all stored in memory? If so, migrating to a db (mongo?) could enable more complicated queries such as searching inside Arrays fields via indexing. 

This is just speculation at the moment, i'm getting the sense we want to try and keep things simple for now.

**Comment by darenliang** [comment]
I agree, keeping it simple will also make it easier to maintain in the long run.

As for the point about migrating to a DB, I would like to. However, I've had tried in the past to move to MongoDB and it seems really problematic in a hosting aspect. Using a remote DB really messes with the API's latency and throughput (it could be magnitudes slower). I've considered using SQLite, but haven't had the time to tinker with it.

The querying system is a little limited since it's not managed by a database. Maybe this will change in the future once better hosting is available.

**Comment by bill-ahmed** [comment]
Should be good to review now! Let me know if you have any suggestions.

**Comment by darenliang** [comment]
Thanks!

I'll take a look at it later today.

**Comment by darenliang** [comment]
I'm currently reviewing the code, but there's a lot of things I would change.

I'll keep you posted once I gather more info.

**Comment by darenliang** [comment]
I'm closing this issue since I've pushed the initial draft of the new query syntax as its 1.0.0 release.

Thanks for the great work. It definitely was helpful in influencing the initial query draft.

**Pull request closed without merging**
